backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
 collections:
  posts:
    permalink: '/posts/:title/'
 media_folder: '../images'
 media_library: '../images'
